import { useState } from 'react'
import { PremiumGate } from '../PremiumGate'
import { Button } from '../ui/button'
import { PenTool, Copy, RefreshCw, Sparkles } from 'lucide-react'
import { toast } from 'sonner'
import { safeCopy } from '../../lib/clipboard'

const TONES = [
  { id: 'persuasive',   label: 'Persuasive',   emoji: '🎯' },
  { id: 'professional', label: 'Professional', emoji: '💼' },
  { id: 'casual',       label: 'Casual',       emoji: '👋' },
  { id: 'urgent',       label: 'Urgent',       emoji: '⚡' },
] as const

type Variation = { headline: string; body: string }

export function AdCopyWriterPanel() {
  const [productDescription, setProductDescription] = useState('')
  const [tone, setTone] = useState<typeof TONES[number]['id']>('persuasive')
  const [variations, setVariations] = useState<Variation[]>([])
  const [isLoading, setIsLoading] = useState(false)

  const generate = async () => {
    if (!productDescription.trim()) {
      toast.error('Describe your product or service first')
      return
    }
    setIsLoading(true)
    try {
      const result = await window.electronAPI?.ai?.generateAdCopy(productDescription.trim(), tone)
      if (result?.success && result.variations && result.variations.length > 0) {
        setVariations(result.variations)
      } else {
        toast.error(result?.error ? `AI error: ${result.error}` : 'AI returned no copy. Please try again.')
      }
    } catch {
      toast.error('Failed to reach AI service. Please try again.')
    } finally {
      setIsLoading(false)
    }
  }

  const copyVariation = async (v: Variation) => {
    const ok = await safeCopy(`${v.headline}\n${v.body}`)
    if (ok) toast.success('Copied to clipboard ✓')
    else toast.error('Copy failed — please select the text manually')
  }

  return (
    <PremiumGate
      feature="AI Ad Copy Writer"
      description="Paste your product or service and get headline + body copy variations generated by AI."
      icon="✍️"
    >
      <div className="flex flex-col h-full">
        <div className="flex items-center gap-3 px-6 py-4 border-b border-border/50 bg-background/95 backdrop-blur sticky top-0 z-10"
          style={{ WebkitAppRegion: 'drag' } as React.CSSProperties}>
          <div className="w-8 h-8 rounded-xl bg-violet-100 dark:bg-violet-950/50 flex items-center justify-center text-violet-600 dark:text-violet-400" style={{ WebkitAppRegion: 'no-drag' } as React.CSSProperties}>
            <PenTool className="h-4 w-4" />
          </div>
          <div style={{ WebkitAppRegion: 'no-drag' } as React.CSSProperties}>
            <h2 className="text-sm font-semibold text-foreground">AI Ad Copy Writer</h2>
            <p className="text-[11px] text-muted-foreground">Headlines & body copy for your ads</p>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto p-6 space-y-5">
          <div className="space-y-2">
            <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
              Describe your product or service
            </label>
            <textarea
              value={productDescription}
              onChange={(e) => setProductDescription(e.target.value)}
              placeholder="e.g. &quot;A subscription box for artisanal coffee beans, shipped monthly&quot;"
              rows={4}
              className="w-full resize-none rounded-xl bg-muted/40 border border-border/50 text-sm text-foreground placeholder:text-muted-foreground px-4 py-3 focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary/50"
            />
          </div>

          <div className="space-y-2">
            <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
              Tone
            </label>
            <div className="grid grid-cols-4 gap-2">
              {TONES.map((t) => (
                <button
                  key={t.id}
                  onClick={() => setTone(t.id)}
                  className={`flex flex-col items-center gap-1 p-3 rounded-xl border text-xs font-semibold transition-all ${
                    tone === t.id
                      ? 'bg-primary text-primary-foreground border-primary shadow-sm'
                      : 'bg-card border-border/50 text-muted-foreground hover:border-primary/40'
                  }`}
                >
                  <span className="text-base">{t.emoji}</span>
                  {t.label}
                </button>
              ))}
            </div>
          </div>

          <Button className="w-full gap-2" onClick={generate} disabled={isLoading || !productDescription.trim()}>
            {isLoading ? (
              <><RefreshCw className="h-4 w-4 animate-spin" /> Generating...</>
            ) : (
              <><Sparkles className="h-4 w-4" /> Generate Ad Copy</>
            )}
          </Button>

          {variations.length > 0 && (
            <div className="space-y-2">
              <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                Variations — click to copy
              </label>
              {variations.map((v, i) => (
                <div key={i} className="w-full p-4 rounded-xl bg-card border border-border/50 text-sm text-foreground leading-relaxed space-y-1.5">
                  <div className="flex items-start gap-3">
                    <span className="text-xs font-bold text-muted-foreground mt-0.5 shrink-0">#{i + 1}</span>
                    <div className="flex-1 min-w-0">
                      <p className="font-semibold">{v.headline}</p>
                      <p className="text-muted-foreground mt-0.5">{v.body}</p>
                    </div>
                  </div>
                  <div className="flex gap-2 justify-end">
                    <button
                      onClick={() => copyVariation(v)}
                      className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-border/50 text-xs font-medium text-muted-foreground hover:text-foreground hover:border-border transition-all"
                    >
                      <Copy className="h-3 w-3" /> Copy
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </PremiumGate>
  )
}
